In [1]:
import numpy.random as nr
import numpy as np
import json

In [2]:
import pandas

In [3]:
alfa, gamma = (round(x,2) for x in nr.random(2))
tractor = nr.choice([0,1], 40, p=[0.7, 0.3])
afinidad = nr.choice([0,1], [40, 40])
afinidad = np.tril(afinidad) + np.tril(afinidad, -1).T
experiencia = [round(min(nr.exponential(0.2), 1),2) for i in range(40)]

In [5]:
print(alfa, gamma)
pandas.DataFrame(tractor)

0.16 0.09

    0
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   1
10  0
11  0
12  1
13  0
14  0
15  0
16  0
17  0
18  1
19  1
20  0
21  0
22  0
23  1
24  0
25  1
26  0
27  1
28  1
29  1
30  0
31  0
32  1
33  0
34  1
35  1
36  0
37  0
38  0
39  0

In [6]:
pandas.DataFrame(afinidad)

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,0,1,0,1,1,0,1,1,0,0,...,0,0,0,1,0,0,0,1,1,1
1,1,0,1,0,1,0,1,1,0,0,...,1,0,1,1,0,1,0,1,0,1
2,0,1,1,0,0,1,1,0,0,1,...,0,0,1,1,0,1,1,1,0,0
3,1,0,0,1,1,1,1,1,0,0,...,1,0,1,1,0,1,1,0,0,0
4,1,1,0,1,0,0,0,0,1,1,...,0,0,0,1,1,1,1,0,0,1
5,0,0,1,1,0,0,1,1,1,0,...,0,0,0,1,1,1,1,0,0,1
6,1,1,1,1,0,1,0,1,0,1,...,1,1,0,1,1,0,0,0,0,1
7,1,1,0,1,0,1,1,1,0,1,...,1,1,0,1,0,0,0,1,1,0
8,0,0,0,0,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,0
9,0,0,1,0,1,0,1,1,1,1,...,1,1,0,1,0,1,0,1,1,1
10,1,1,1,0,0,1,1,0,1,1,...,1,1,0,0,0,0,1,0,1,1
11,1,0,0,1,0,1,1,1,0,1,...,0,0,0,1,0,1,1,1,0,1
12,0,1,0,1,0,0,0,1,0,1,...,0,1,0,0,1,1,1,1,0,0
13,1,0,1,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,1,0,0,1,1,1,1,1,1,1,...,0,0,1,0,0,1,1,1,1,1
15,1,1,0,1,0,1,0,1,1,0,...,1,0,0,0,1,0,0,1,0,0
16,0,1,1,0,1,0,1,0,1,1,...,1,1,1,0,0,1,0,1,1,1
17,1,0,0,0,1,0,1,1,1,0,...,0,1,0,1,1,0,0,0,0,0
18,1,1,0,1,1,1,0,1,1,1,...,1,1,1,1,1,0,0,0,1,0
19,1,1,1,0,0,0,0,1,0,0,...,1,1,0,1,0,0,0,0,0,0
20,1,1,1,0,0,0,1,1,1,1,...,1,1,1,0,1,1,0,0,0,1
21,1,0,0,0,1,1,1,0,1,1,...,1,0,1,1,1,0,0,1,1,0
22,1,1,1,1,0,1,1,0,0,1,...,1,1,1,1,0,1,1,0,0,1
23,1,1,1,1,1,1,0,1,1,0,...,1,0,1,0,1,1,1,0,0,1
24,1,1,1,1,1,1,0,0,1,1,...,0,1,1,0,1,0,0,0,0,1
25,0,0,0,0,1,1,0,1,0,1,...,1,0,0,0,1,1,1,1,0,0
26,1,0,0,1,1,0,0,1,1,1,...,0,0,1,1,0,1,0,1,1,0
27,0,0,1,0,0,1,0,0,1,1,...,0,0,1,1,1,1,0,0,1,1
28,0,1,0,1,1,0,1,1,0,0,...,0,0,0,0,1,0,0,1,0,1
29,0,0,0,1,0,1,0,1,0,1,...,1,0,0,0,0,1,0,0,0,1
30,0,1,0,1,0,0,1,1,1,1,...,1,1,1,1,0,1,0,1,0,0
31,0,0,0,0,0,0,1,1,1,1,...,1,1,1,1,0,1,1,0,0,1
32,0,1,1,1,0,0,0,0,1,0,...,1,1,1,1,1,1,1,1,1,1
33,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,0
34,0,0,0,0,1,1,1,0,1,0,...,0,0,1,1,1,1,1,1,1,0
35,0,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,0,1,0,0
36,0,0,1,1,1,1,0,0,1,0,...,0,1,1,1,1,0,1,1,1,0
37,1,1,1,0,0,0,0,1,1,1,...,1,0,1,1,1,1,1,0,1,1
38,1,0,0,0,0,0,0,1,1,1,...,0,0,1,0,1,0,1,1,0,0
39,1,1,0,0,1,1,1,0,0,1,...,0,1,1,0,0,0,0,1,0,0

In [7]:
pandas.DataFrame(experiencia)

       0
0   0.53
1   0.40
2   0.04
3   0.23
4   0.14
5   0.09
6   0.19
7   0.25
8   0.50
9   0.12
10  0.01
11  0.02
12  0.34
13  0.05
14  0.20
15  0.01
16  0.02
17  0.51
18  0.06
19  0.11
20  0.54
21  0.56
22  0.09
23  0.09
24  0.24
25  0.27
26  0.02
27  0.04
28  0.05
29  0.18
30  0.68
31  0.21
32  0.04
33  0.20
34  0.06
35  0.00
36  0.17
37  0.13
38  0.13
39  0.13

In [8]:
datos = {'alfa': alfa, 'gamma': gamma, 'tractor': tractor.tolist(), 'afinidad': afinidad.tolist(), 'experiencia': experiencia}
with open('datos.json','w') as f:
    json.dump(datos, f)